//Solution 1

public class Kata {

  static char triangle(final String row) {
  
    if (row.length() == 1) return row.charAt(0);
    
    String nextRow = "";
    for (int i = 1; i < row.length(); i++) {
      char c1 = row.charAt(i-1), c2 = row.charAt(i);
      switch (c1) {
        case 'R': nextRow += c2=='R'?'R':c2=='G'?'B':'G'; break;
        case 'G': nextRow += c2=='R'?'B':c2=='G'?'G':'R'; break;
        case 'B': nextRow += c2=='R'?'G':c2=='G'?'R':'B'; break;
      }    
    }
    return triangle(nextRow); // recurse
  }

}

//Solution 2


public class Kata {
    public static char getChar(char c1, char c2) {
        return c1 == c2 ? c1 : java.util.Arrays.stream(new Character[]{'R', 'B', 'G'}).filter(c -> !c.equals(c1) && !c.equals(c2)).findFirst().orElse('㋛');
    }

    public static char triangle(String s) {
        while (s.length() > 1) {
            StringBuilder sb = new StringBuilder();
            for (int i = 0; i < s.length(); i++) {
                if (i + 1 < s.length()) sb.append(getChar(s.charAt(i), s.charAt(i + 1)));
                else s = sb.toString();
            }
        }
        return s.charAt(0);
    }
}


DESCRIPTION:
If you finish this kata, you can try Insane Coloured Triangles by Bubbler, which is a much harder version of this one.

A coloured triangle is created from a row of colours, each of which is red, green or blue. Successive rows, each containing one fewer colour than the last, are generated by considering the two touching colours in the previous row. If these colours are identical, the same colour is used in the new row. If they are different, the missing colour is used in the new row. This is continued until the final row, with only a single colour, is generated.

The different possibilities are:

Colour here:        G G        B G        R G        B R
Becomes colour:      G          R          B          G
With a bigger example:

R R G B R G B B
 R B R G B R B
  G G B R G G
   G R G B G
    B B R R
     B G R
      R B
       G
You will be given the first row of the triangle as a string and its your job to return the final colour which would appear in the bottom row as a string. In the case of the example above, you would the given RRGBRGBB you should return G.

The input string will only contain the uppercase letters R, G, B and there will be at least one letter so you do not have to test for invalid input.
If you are only given one colour as the input, return that colour.
Adapted from the 2017 British Informatics Olympiad

LOGIC STRINGS ALGORITHMS
